# @package _group_
_target_: bela.datamodule.joint_el_datamodule.JointELDataModule
train_path: data/train_joint.txt
val_path: data/eval_joint.txt
test_path: data/test_joint.txt
ent_catalogue_idx_path: data/es_xlm_ent_idx.txt

batch_size: 64
drop_last: False
