defaults:
  - config
  - datamodule: joint_el_datamodule
  - task/transform: joint_el_bert_transform
  - task/model: bert
  - task/optim: adamw
  - trainer: gpu_1_host

task:
  _target_: bela.task.joint_el_task.ClusterTask
  load_from_checkpoint: /data/home/kassner/BELA/outputs/2021-10-26/09-40-28/lightning_logs/version_0/checkpoints/checkpoint_best.ckpt

datamodule:
  train_path: /fsx/kassner/wikipedia/en_matcha_jointtrain.jsonl
  val_path: /fsx/kassner/wikipedia/en_matcha_jointdev.jsonl
  test_path: /fsx/kassner/wikipedia/en_matcha_test.jsonl

trainer:
  gpus: 8

checkpoint_callback:
    monitor: valid_boe_f1
