defaults:
  - config
  - datamodule: joint_el_datamodule
  - task/transform: joint_el_bert_transform
  - task/model: bert
  - task/optim: adamw
  - trainer: gpu_1_host

task:
  _target_: bela.task.cluster_task.ClusterTask
  load_from_checkpoint: /fsx/kassner/models/jointtrained_t1/0/lightning_logs/version_492060/checkpoints/checkpoint_best.ckpt
  save_embeddings_path: mention_encodings 

datamodule:
  test_path: /fsx/kassner/OSCAR/processed/cnn_bbc_news.jsonl
  ent_catalogue_idx_path: /data/home/kassner/BELA/data/blink/en_bert_ent_idx.txt
  novel_entity_idx_path: /data/home/kassner/BELA/data/blink/novel_entities_filtered.jsonl

trainer:
  gpus: 1

checkpoint_callback:
    monitor: valid_boe_f1
