defaults:
  - config
  - datamodule: joint_el_datamodule
  - task/transform: joint_el_bert_transform
  - task/model: bert
  - task/optim: adamw
  - trainer: gpu_1_host

task:
  _target_: bela.task.joint_el_task.ClusterTask
  load_from_checkpoint: /checkpoints/kassner/hydra_outputs/main/2021-11-09-215754/0/lightning_logs/version_492060/checkpoints/checkpoint_best.ckpt
  save_embeddings_path: mention_encodings 

datamodule:
  test_path: /fsx/kassner/OSCAR/subset/t1/cnn_bbc_matcha_jointtrain.jsonl
  ent_catalogue_idx_path: /data/home/kassner/BELA/data/blink/en_bert_ent_idx.txt

trainer:
  gpus: 3

checkpoint_callback:
    monitor: valid_boe_f1
