language_model: bert-large-uncased
log_dir: /checkpoints/matzeni/duck/logs
ckpt_dir: /checkpoints/matzeni/duck/checkpoints
run_name: duck
debug: False

defaults:
  - optim: adamw
  - trainer: 1gpu
  - _self_

data:
  _target_: duck.datamodule.EdDuckDataModule
  train_path: /fsx/matzeni/data/GENRE/blink-train-kilt.jsonl
  val_paths:
    aida_train: /fsx/matzeni/data/GENRE/aida-train-kilt.jsonl
    blink_dev: /fsx/matzeni/data/GENRE/blink-dev-kilt.jsonl
    aida: /fsx/matzeni/data/GENRE/aida-test-kilt.jsonl
    aida_dev: /fsx/matzeni/data/GENRE/aida-dev-kilt.jsonl
    ace2004: /fsx/matzeni/data/GENRE/ace2004-test-kilt.jsonl
    acquaint: /fsx/matzeni/data/GENRE/aquaint-test-kilt.jsonl
    clueweb: /fsx/matzeni/data/GENRE/clueweb-test-kilt.jsonl
    msnbc: /fsx/matzeni/data/GENRE/msnbc-test-kilt.jsonl
    wiki: /fsx/matzeni/data/GENRE/wiki-test-kilt.jsonl
  test_paths:
    aida_test: /fsx/matzeni/data/GENRE/aida-test-kilt.jsonl
    ace2004: /fsx/matzeni/data/GENRE/ace2004-test-kilt.jsonl
    acquaint: /fsx/matzeni/data/GENRE/aquaint-test-kilt.jsonl
    clueweb: /fsx/matzeni/data/GENRE/clueweb-test-kilt.jsonl
    msnbc: /fsx/matzeni/data/GENRE/msnbc-test-kilt.jsonl
    wiki: /fsx/matzeni/data/GENRE/wiki-test-kilt.jsonl
  ent_to_rel_path: /fsx/matzeni/data/duck/ent_to_rel.json
  wikipedia_to_wikidata_path: /fsx/matzeni/data/duck/wikipedia_to_wikidata_en.pkl
  ent_catalogue_idx_path: /fsx/matzeni/data/duck/ent_idx.txt
  ent_catalogue_data_path: /fsx/matzeni/data/duck/bert_ent_256_tok_ids.h5
  rel_catalogue_idx_path: /fsx/matzeni/data/duck/rel_idx.txt
  rel_catalogue_data_path: /fsx/matzeni/data/duck/bert_rel_256_repr.h5
  # neighbors_path: /fsx/matzeni/data/duck/duck_neighbors.json
  stop_rels_path: /fsx/matzeni/data/duck/stop_rels.jsonl
  batch_size: 32
  num_neighbors_per_entity: 1
  shuffle: True
  transform:
    _target_: duck.datamodule.DuckTransform
    model_path: ${language_model}
    max_mention_len: 128
    max_entity_len: 128
    max_relation_len: 32

task:
  _target_: duck.task.Duck

duck:
  # rel_to_box_model: ${ckpt_dir}/r2b_wd/r2b_wd_origin_epoch=79_kldiv_train=0.0018_last.ckpt
  base_model:
      _target_: bela.models.hf_encoder.HFEncoder
      model_path: ${language_model}
  boxes:
    intersection_temperature: 0.0001
    volume_temperature: 0.1
    parametrization: relu
  num_negative_boxes: 30 
  duck_loss:
    _target_: duck.task.duck_entity_disambiguation.DuckMaxMarginRankingLoss
    margin: 20.0
    inside_weight: 0.2
    # _target_: duck.task.duck_entity_disambiguation.GumbelBoxMembershipNLLLoss
    # intersection_temperature: 0.1
    # _target_: duck.task.duck_entity_disambiguation.DuckNCEMarginLoss
    # margin: 25
    # inside_weight: 0.2

trainer:
  max_epochs: 30
  min_epochs: 10
  num_sanity_val_steps: 0
  log_every_n_steps: 1

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_f1
  every_n_train_steps: 10001
  mode: max
  save_last: true
  verbose: true
  filename: ${run_name}_{epoch}_{val_f1:.3f}
  save_top_k: 1
  dirpath: ${ckpt_dir}

ablations:
  blink: False
  relations_as_points: False
  joint_ent_rel_encoding: False

hydra:
  run:
    dir: .
