language_model: bert-large-uncased
log_dir: /checkpoints/matzeni/duck/logs
ckpt_dir: /checkpoints/matzeni/duck/checkpoints
run_name: duck
debug: False

defaults:
  - optim: adamw
  - _self_

data:
  _target_: duck.datamodule.EdDuckDataModule
  train_path: /fsx/matzeni/data/GENRE/aida-train-kilt.jsonl
  val_path: /fsx/matzeni/data/GENRE/aida-dev-kilt.jsonl
  test_path: /fsx/matzeni/data/GENRE/aida-test-kilt.jsonl
  ent_to_rel_path: /fsx/matzeni/data/duck/ent_to_rel.json
  ent_catalogue_idx_path: /fsx/matzeni/data/duck/ent_idx.txt
  ent_catalogue_data_path: /fsx/matzeni/data/duck/bert_ent_256_tok_ids.h5
  rel_catalogue_idx_path: /fsx/matzeni/data/duck/rel_idx.txt
  # rel_catalogue_data_path: /fsx/matzeni/data/duck/bert_rel_256_repr.h5
  neighbors_path: /fsx/matzeni/data/duck/duck_neighbors.json
  stop_rels_path: /fsx/matzeni/data/duck/stop_rels.jsonl
  # pretrained_relations: True
  batch_size: 32
  num_neighbors_per_entity: 1
  shuffle: True
  transform:
    _target_: duck.datamodule.DuckTransform
    model_path: ${language_model}
    max_mention_len: 128
    max_entity_len: 128
    max_relation_len: 32

task:
  _target_: duck.task.Duck

duck:
  rel_to_box_model: ${ckpt_dir}/r2b_wd/r2b_wd_uniform_epoch=152_kldiv_train=0.0136_last.ckpt
  base_model:
      _target_: bela.models.hf_encoder.HFEncoder
      model_path: ${language_model}
  boxes:
    intersection_temperature: 0.0001
    volume_temperature: 0.1
    rel_threshold: 1
  box_encoder:
    num_layers: 3
    dropout: 0.1
    attn_heads: 8
    activation: softmax
    margin: 0.5
  duck_loss: jaccard_mse
  in_batch_neighbors: 5

trainer:
  max_epochs: 10
  min_epochs: 10
  val_check_interval: 100
  accelerator: gpu
  devices: 1
  num_nodes: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 1
  #gradient_clip_val: 2.0
  #accumulate_grad_batches: 1
  #plugins: ddp_sharded
  #strategy: ddp_sharded

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: duck_loss
  every_n_train_steps: 100
  mode: min 
  save_last: true
  verbose: true
  filename: ${run_name}_{epoch}_{duck_loss:.3f}
  save_top_k: 1
  dirpath: ${ckpt_dir}

hydra:
  run:
    dir: .
