data:
  data_dir: /fsx/matzeni/data/GENRE
  train_path: ${data.data_dir}/aida-train-kilt.jsonl
  val_path: ${data.data_dir}/aida-dev-kilt.jsonl
  test_path: ${data.data_dir}/aida-test-kilt.jsonl
  ent_catalogue_idx_path: /fsx/matzeni/data/duck/bert_ent_256_idx.txt
  ent_catalogue_path: /fsx/matzeni/data/duck/bert_ent_256.h5
  rel_catalogue_idx_path: /fsx/matzeni/data/duck/bert_rel_256_idx.txt
  rel_catalogue_path: /fsx/matzeni/data/duck/bert_rel_256.h5
  ent_to_rel_path: /fsx/matzeni/data/duck/ent_to_rel.json
  neighbors_path: /fsx/matzeni/data/duck/duck_neighbors.json


max_mention_len: 128
max_entity_len: 128
max_relation_len: 64
batch_size: 2
language_model: bert-large-uncased


hydra:
  run:
    dir: .