log_dir: /checkpoints/matzeni/duck/logs
ckpt_dir: /checkpoints/matzeni/duck/checkpoints
run_name: rel_to_box
debug: false

resume_path: ${ckpt_dir}/r2b_wd_origin_epoch=49_kldiv_train=0.0053_last.ckpt

defaults:
  - optim: adamw
  - _self_
  - trainer: 1gpu
  
optim:
  lr: 1e-3

data:
  _target_: duck.datamodule.RelToBoxDataModule
  rel_probs_path: /fsx/matzeni/data/duck/rel_probs.json
  # rel_catalogue_idx_path: /fsx/matzeni/data/duck/sample_aida_rels.txt
  rel_catalogue_idx_path: /fsx/matzeni/data/duck/rel_idx.txt
  batch_size: 100000
  target_prob_threshold: null
  only_marginal: false
  only_conditional: false
  shuffle: false
  num_workers: 10

task:
  _target_: duck.task.RelToBox

rel_to_box:
  dim: 1024
  boxes:
    intersection_temperature: 0.0001
    volume_temperature: 0.1
    parametrization: sigmoid  # options: uniform, gaussian_margin, sigmoid, softplus 

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: kldiv_train
  every_n_train_steps: 1000
  mode: min 
  save_last: true
  verbose: true
  filename: ${run_name}_{epoch}_{kldiv_train:.4f}
  save_top_k: 1
  dirpath: ${ckpt_dir}

trainer:
  max_epochs: 1000
  min_epochs: 300
  check_val_every_n_epoch: 40

hydra:
  run:
    dir: .
  job:
    name: ${run_name}
