log_dir: /checkpoints/matzeni/duck/logs
ckpt_dir: /checkpoints/matzeni/duck/checkpoints
run_name: rel_to_box
debug: false

pretrained_model_path: null

defaults:
  - optim: adamw
  - _self_

optim:
  lr: 1e-3

data:
  _target_: duck.datamodule.RelToBoxDataModule
  rel_probs_path: /fsx/matzeni/data/duck/rel_probs.json
  # rel_catalogue_idx_path: /fsx/matzeni/data/duck/sample_aida_rels.txt
  rel_catalogue_idx_path: /fsx/matzeni/data/duck/rel_idx.txt
  batch_size: 100000
  target_prob_threshold: null
  only_marginal: false
  only_conditional: false
  shuffle: false
  num_workers: 10

task:
  _target_: duck.task.RelToBox

rel_to_box:
  dim: 1024
  boxes:
    intersection_temperature: 0.0001
    volume_temperature: 0.1
    parametrization: sigmoid  # options: uniform, gaussian_margin, sigmoid, softplus 
  # regularization:
  #   _target_: duck.box_tensors.regularization.L2SideBoxRegularizer
  #   weight: 1.0
  #   reduction: sum

trainer:
  max_epochs: 1000
  min_epochs: 300
  accelerator: gpu
  devices: 1
  num_nodes: 1
  log_every_n_steps: 10
  num_sanity_val_steps: 10
  check_val_every_n_epoch: 10

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: kldiv_train
  every_n_train_steps: 1000
  mode: min 
  save_last: true
  verbose: true
  filename: ${run_name}_{epoch}_{kldiv_train:.4f}
  save_top_k: 1
  dirpath: ${ckpt_dir}

hydra:
  run:
    dir: .