input_path: /fsx/matzeni/data/duck/kilt_knowledgesource.jsonl
kb_path: null # /fsx/matzeni/data/duck/wikipedia_to_wikidata_en.pkl
output_tok_ids_path: /fsx/matzeni/data/duck/bert_ent_256_tok_ids.h5
output_idx_path: /fsx/matzeni/data/duck/ent_idx.txt
output_repr_path: null
max_seq_length: 256
batch_size: 128
model: bert-large-uncased
label_key: wikipedia_title
text_key: text