input_path: /fsx/matzeni/data/duck/properties.json
output_tok_ids_path: /fsx/matzeni/data/duck/bert_rel_256_tok_ids.h5
output_idx_path: /fsx/matzeni/data/duck/bert_rel_256_idx.txt
output_repr_path: /fsx/matzeni/data/duck/bert_rel_256_repr.h5
max_seq_length: 128
batch_size: 128
model: bert-large-uncased
label_key: label
text_key: description
compute_representations: True