ent_catalogue_idx_path: /fsx/matzeni/data/duck/bert_ent_256_idx.txt
ent_catalogue_path: /fsx/matzeni/data/duck/bert_ent_256.h5
rel_catalogue_idx_path: /fsx/matzeni/data/duck/bert_rel_256_idx.txt
rel_catalogue_path: /fsx/matzeni/data/duck/bert_rel_256.h5
ent_to_rel_path: /fsx/matzeni/data/duck/ent_to_rel.json
index_path: /fsx/matzeni/data/duck/duck_index_flat.faiss
gpu: True
batch_size: 100
stop_rels_path: /fsx/matzeni/data/duck/stop_relations.jsonl
neighbors_path: /fsx/matzeni/data/duck/duck_neighbors.json
num_neighbors: 10

hnsw:
  branching_factor: 64
  ef_search: 256
  ef_construction: 256