defaults:
  - config
  - datamodule: joint_el_datamodule
  - task/transform: joint_el_xlmr_transform
  - task/model: xlmr
  - task/optim: adamw
  - trainer: gpu_1_host

task:
  _target_: bela.task.joint_el_task.JointELTask
  embeddings_path: /data/home/kassner/BELA/data/matcha/en/en_embeddings.pt
  faiss_index_path: /data/home/kassner/BELA/data/matcha/en/en_index.faiss
  load_from_checkpoint: /checkpoints/movb/hydra_outputs/main/2021-09-13-001149/0/lightning_logs/version_89311/checkpoints/checkpoint_best.ckpt

datamodule:
  train_path: /fsx/kassner/OSCAR/subset/t1/cnn_bbc_matcha_jointtrain_subset.jsonl
  val_path: /fsx/kassner/OSCAR/subset/t1/cnn_bbc_matcha_jointtrain_subset.jsonl
  test_path: /fsx/kassner/OSCAR/subset/t1/cnn_bbc_matcha_jointtrain_subset.jsonl
  ent_catalogue_idx_path: /data/home/kassner/BELA/data/matcha/en/en_xlm_ent_idx.txt
  batch_size: 1

checkpoint_callback:
    monitor: valid_boe_f1

trainer:
    gpus: 3
